# Generated by Django 3.2.7 on 2023-04-05 22:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_portfolio_portfoliodb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodb',
            name='compnay',
            field=jsonfield.fields.JSONField(),
        ),
    ]
